//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExplorerWF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveNbFichier {
            get {
                return ((string)(this["SaveNbFichier"]));
            }
            set {
                this["SaveNbFichier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveNbFichierCs {
            get {
                return ((string)(this["SaveNbFichierCs"]));
            }
            set {
                this["SaveNbFichierCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveNomFichierLePlusLong {
            get {
                return ((string)(this["SaveNomFichierLePlusLong"]));
            }
            set {
                this["SaveNomFichierLePlusLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDossierSelectionne {
            get {
                return ((string)(this["SaveDossierSelectionne"]));
            }
            set {
                this["SaveDossierSelectionne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveCheckedNbFichier {
            get {
                return ((bool)(this["SaveCheckedNbFichier"]));
            }
            set {
                this["SaveCheckedNbFichier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveCheckedNbFichierCs {
            get {
                return ((bool)(this["SaveCheckedNbFichierCs"]));
            }
            set {
                this["SaveCheckedNbFichierCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveCheckedNomFichierLePlusLong {
            get {
                return ((bool)(this["SaveCheckedNomFichierLePlusLong"]));
            }
            set {
                this["SaveCheckedNomFichierLePlusLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveCheckedListeFichiersCsproj {
            get {
                return ((bool)(this["SaveCheckedListeFichiersCsproj"]));
            }
            set {
                this["SaveCheckedListeFichiersCsproj"] = value;
            }
        }
    }
}
